# Generated by Django 4.0.3 on 2023-07-26 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('idx', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('Algebra', 'Algebra'), ('Combinatorics', 'Combinatorics'), ('Geometry', 'Geometry'), ('Number Theory', 'Number Theory')], max_length=30)),
                ('source', models.CharField(choices=[('Euclidean Geometry in Mathematical Olympiads by Evan Chen', 'Euclidean Geometry in Mathematical Olympiads by Evan Chen'), ('Modern Olympiad Number Theory by Aditya Khurmi', 'Modern Olympiad Number Theory by Aditya Khurmi'), ("Stephan Wagner's Combinatorics Handout", "Stephan Wagner's Combinatorics Handout"), ('Olympiad Combinatorics by Pranav Sriram', 'Olympiad Combinatorics by Pranav Sriram'), ('Secrets in Inequalities (Volume 1) by Pham Kim Hung', 'Secrets in Inequalities (Volume 1) by Pham Kim Hung'), ('Secrets in Inequalities (Volume 2) by Pham Kim Hung', 'Secrets in Inequalities (Volume 2) by Pham Kim Hung'), ("Evan Chen's Functional Equations Handout", "Evan Chen's Functional Equations Handout")], max_length=200)),
                ('pdf', models.FileField(upload_to='units/')),
                ('solutions', models.FileField(blank=True, null=True, upload_to='solutions/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
